-- ===============================================
-- SEQUENCES
-- ===============================================

CREATE SEQUENCE "MOMOAPI"."ACCOUNT_SEQ"
  MINVALUE 1
  MAXVALUE 9999999999999999999999999999
  INCREMENT BY 1
  START WITH 1
  NOCACHE
  NOORDER
  NOCYCLE;

CREATE SEQUENCE "MOMOAPI"."ACCOUNT_PERMISSION_PROGRAM_SEQ"
  MINVALUE 1
  MAXVALUE 9999999999999999999999999999
  INCREMENT BY 1
  START WITH 1
  NOCACHE
  NOORDER
  NOCYCLE;

CREATE SEQUENCE "MOMOAPI"."ACCOUNT_ACTION_HISTORY_SEQ"
  MINVALUE 1
  MAXVALUE 9999999999999999999999999999
  INCREMENT BY 1
  START WITH 1
  NOCACHE
  NOORDER
  NOCYCLE;

CREATE SEQUENCE "MOMOAPI"."AP_KEY_IV_SEQ"
  MINVALUE 1
  MAXVALUE 9999999999999999999999999999
  INCREMENT BY 1
  START WITH 1
  NOCACHE
  NOORDER
  NOCYCLE;

CREATE SEQUENCE "MOMOAPI"."LOGIN_HISTORY_ID"
  MINVALUE 1
  MAXVALUE 9999999999999999999999999999
  INCREMENT BY 1
  START WITH 1
  NOCACHE
  NOORDER
  NOCYCLE;

CREATE SEQUENCE "MOMOAPI"."MENU_SEQ"
  MINVALUE 1
  MAXVALUE 9999999999999999999999999999
  INCREMENT BY 1
  START WITH 1
  NOCACHE
  NOORDER
  NOCYCLE;

CREATE SEQUENCE "MOMOAPI"."PROGRAM_SEQ"
  MINVALUE 1
  MAXVALUE 9999999999999999999999999999
  INCREMENT BY 1
  START WITH 1
  NOCACHE
  NOORDER
  NOCYCLE;

CREATE SEQUENCE "MOMOAPI"."ROLE_SEQ"
  MINVALUE 1
  MAXVALUE 9999999999999999999999999999
  INCREMENT BY 1
  START WITH 1
  NOCACHE
  NOORDER
  NOCYCLE;

CREATE SEQUENCE "MOMOAPI"."ROLE_PERMISSION_PROGRAM_SEQ"
  MINVALUE 1
  MAXVALUE 9999999999999999999999999999
  INCREMENT BY 1
  START WITH 1
  NOCACHE
  NOORDER
  NOCYCLE;

-- ===============================================
-- TABEL DASAR (TANPA FOREIGN KEY CONSTRAINTS)
-- ===============================================

-- Table: ROLE (DIBUAT PERTAMA)
CREATE TABLE "MOMOAPI"."ROLE" (
  "ROLE_ID" NUMBER(18,0) DEFAULT "MOMOAPI"."ROLE_SEQ"."NEXTVAL" NOT NULL,
  "ROLE_NAME" VARCHAR2(255 BYTE),
  CONSTRAINT "ROLE_PK" PRIMARY KEY ("ROLE_ID")
) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "MOMO";

COMMENT ON TABLE "MOMOAPI"."ROLE" IS '角色';
COMMENT ON COLUMN "MOMOAPI"."ROLE"."ROLE_ID" IS 'KEY';
COMMENT ON COLUMN "MOMOAPI"."ROLE"."ROLE_NAME" IS '角色代碼(ROLE_XXX)';

-- Table: DEPARTMENT (DIBUAT KEDUA)
CREATE TABLE "MOMOAPI"."DEPARTMENT" (
  "DEPARTMENT_ID" NUMBER(18,0) NOT NULL,
  "DEPARTMENT_NAME" NVARCHAR2(100),
  "ENABLED" VARCHAR2(1 BYTE) DEFAULT 'Y',
  "CREATE_DATE" TIMESTAMP (6),
  "UPDATE_DATE" TIMESTAMP (6),
  "BU_TAG" VARCHAR2(10 BYTE),
  CONSTRAINT "DEPARTMENT_PK" PRIMARY KEY ("DEPARTMENT_ID")
) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "MOMO";

COMMENT ON TABLE "MOMOAPI"."DEPARTMENT" IS '部門別';
COMMENT ON COLUMN "MOMOAPI"."DEPARTMENT"."DEPARTMENT_ID" IS '部門ID';
COMMENT ON COLUMN "MOMOAPI"."DEPARTMENT"."DEPARTMENT_NAME" IS '部門名稱';
COMMENT ON COLUMN "MOMOAPI"."DEPARTMENT"."ENABLED" IS '是否啟用';
COMMENT ON COLUMN "MOMOAPI"."DEPARTMENT"."CREATE_DATE" IS '建立時間';
COMMENT ON COLUMN "MOMOAPI"."DEPARTMENT"."UPDATE_DATE" IS '更新時間';

-- Table: MENU (DIBUAT KETIGA)
CREATE TABLE "MOMOAPI"."MENU" (
  "MENU_ID" NUMBER(18,0) DEFAULT "MOMOAPI"."MENU_SEQ"."NEXTVAL" NOT NULL,
  "MENU_NAME" NVARCHAR2(150),
  "ORDER_NO" NUMBER(10,0),
  "CREATE_DATE" TIMESTAMP (6),
  "CREATE_ACCOUNT" NUMBER(18,0),
  "UPDATE_DATE" TIMESTAMP (6),
  "UPDATE_ACCOUNT" NUMBER(18,0),
  CONSTRAINT "MENU_PK" PRIMARY KEY ("MENU_ID")
) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "MOMO";

COMMENT ON TABLE "MOMOAPI"."MENU" IS '功能選單(父標題)';
COMMENT ON COLUMN "MOMOAPI"."MENU"."MENU_ID" IS 'KEY';
COMMENT ON COLUMN "MOMOAPI"."MENU"."MENU_NAME" IS '功能名稱';
COMMENT ON COLUMN "MOMOAPI"."MENU"."ORDER_NO" IS '排序';
COMMENT ON COLUMN "MOMOAPI"."MENU"."CREATE_DATE" IS '建立時間';
COMMENT ON COLUMN "MOMOAPI"."MENU"."CREATE_ACCOUNT" IS '建立ID';
COMMENT ON COLUMN "MOMOAPI"."MENU"."UPDATE_DATE" IS '更新時間';
COMMENT ON COLUMN "MOMOAPI"."MENU"."UPDATE_ACCOUNT" IS '更新ID';

-- Table: ACCOUNT (DIBUAT KEEMPAT, TANPA FOREIGN KEY CONSTRAINTS DULU)
CREATE TABLE "MOMOAPI"."ACCOUNT" (
  "ACCOUNT_ID" NUMBER(18,0) DEFAULT "MOMOAPI"."ACCOUNT_SEQ"."NEXTVAL" NOT NULL,
  "USER_ID" VARCHAR2(120 BYTE),
  "USER_NAME" NVARCHAR2(120),
  "EMAIL" VARCHAR2(255 BYTE),
  "ROLE_ID" NUMBER(18,0),
  "DEPARTMENT_ID" NUMBER(18,0),
  "APPROVABLE" VARCHAR2(1 BYTE) DEFAULT 'N',
  "ENABLED" VARCHAR2(1 BYTE) DEFAULT 'Y',
  "CREATE_DATE" TIMESTAMP (6),
  "CREATE_ACCOUNT" NUMBER(18,0),
  "UPDATE_DATE" TIMESTAMP (6),
  "UPDATE_ACCOUNT" NUMBER(18,0),
  "MOBILE" VARCHAR2(10 BYTE),
  CONSTRAINT "ACCOUNT_PK" PRIMARY KEY ("ACCOUNT_ID")
) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "MOMO";

COMMENT ON TABLE "MOMOAPI"."ACCOUNT" IS '帳號';
COMMENT ON COLUMN "MOMOAPI"."ACCOUNT"."ACCOUNT_ID" IS 'KEY';
COMMENT ON COLUMN "MOMOAPI"."ACCOUNT"."USER_ID" IS '使用者ID';
COMMENT ON COLUMN "MOMOAPI"."ACCOUNT"."USER_NAME" IS '使用者名稱';
COMMENT ON COLUMN "MOMOAPI"."ACCOUNT"."EMAIL" IS 'E-MAIL';
COMMENT ON COLUMN "MOMOAPI"."ACCOUNT"."ROLE_ID" IS '角色ID';
COMMENT ON COLUMN "MOMOAPI"."ACCOUNT"."DEPARTMENT_ID" IS '部門ID';
COMMENT ON COLUMN "MOMOAPI"."ACCOUNT"."APPROVABLE" IS '是否有簽核核決權限';
COMMENT ON COLUMN "MOMOAPI"."ACCOUNT"."ENABLED" IS '是否啟用';
COMMENT ON COLUMN "MOMOAPI"."ACCOUNT"."CREATE_DATE" IS '建立時間';
COMMENT ON COLUMN "MOMOAPI"."ACCOUNT"."CREATE_ACCOUNT" IS '建立人員';
COMMENT ON COLUMN "MOMOAPI"."ACCOUNT"."UPDATE_DATE" IS '更新時間';
COMMENT ON COLUMN "MOMOAPI"."ACCOUNT"."UPDATE_ACCOUNT" IS '更新人員';
COMMENT ON COLUMN "MOMOAPI"."ACCOUNT"."MOBILE" IS '手機號碼';

-- Table: ACCOUNT_ACTION_HISTORY
CREATE TABLE "MOMOAPI"."ACCOUNT_ACTION_HISTORY" (
  "ACCOUNT_ACTION_HISTORY_ID" NUMBER(22,0),
  "EXECUTE_CONTENT" NCLOB,
  "REQUEST_ID" NVARCHAR2(100),
  "ACCOUNT_ID" NUMBER(22,0),
  "EXECUTE_ACCOUNT_ID" NUMBER(22,0),
  "EXECUTE_DATE" TIMESTAMP (6)
) SEGMENT CREATION DEFERRED
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "MOMO"
LOB ("EXECUTE_CONTENT") STORE AS SECUREFILE (
  TABLESPACE "MOMO" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING NOCOMPRESS KEEP_DUPLICATES);

-- Table: ACCOUNT_APPROVAL_SETTING (TANPA FOREIGN KEY CONSTRAINTS DULU)
CREATE TABLE "MOMOAPI"."ACCOUNT_APPROVAL_SETTING" (
  "ACCOUNT_ID" NUMBER(18,0) NOT NULL,
  "L1_APPROVAL" VARCHAR2(1 BYTE) DEFAULT 'N',
  "L1_ACCOUNT_1" NUMBER(18,0),
  "L1_ACCOUNT_2" NUMBER(18,0),
  "L2_APPROVAL" VARCHAR2(1 BYTE) DEFAULT 'N',
  "L2_ACCOUNT_1" NUMBER(18,0),
  "L2_ACCOUNT_2" NUMBER(18,0),
  "CREATE_DATE" TIMESTAMP (6),
  "UPDATE_DATE" TIMESTAMP (6),
  CONSTRAINT "ACCOUNT_APPROVAL_SETTING_PK" PRIMARY KEY ("ACCOUNT_ID")
) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "MOMO";

COMMENT ON TABLE "MOMOAPI"."ACCOUNT_APPROVAL_SETTING" IS '帳號簽核設定';
COMMENT ON COLUMN "MOMOAPI"."ACCOUNT_APPROVAL_SETTING"."ACCOUNT_ID" IS '帳號ID';
COMMENT ON COLUMN "MOMOAPI"."ACCOUNT_APPROVAL_SETTING"."L1_APPROVAL" IS '是否設定第一層簽核人員';
COMMENT ON COLUMN "MOMOAPI"."ACCOUNT_APPROVAL_SETTING"."L1_ACCOUNT_1" IS '第一層簽核人員1';
COMMENT ON COLUMN "MOMOAPI"."ACCOUNT_APPROVAL_SETTING"."L1_ACCOUNT_2" IS '第一層簽核人員2';
COMMENT ON COLUMN "MOMOAPI"."ACCOUNT_APPROVAL_SETTING"."L2_APPROVAL" IS '是否設定第二層簽核人員';
COMMENT ON COLUMN "MOMOAPI"."ACCOUNT_APPROVAL_SETTING"."L2_ACCOUNT_1" IS '第二層簽核人員1';
COMMENT ON COLUMN "MOMOAPI"."ACCOUNT_APPROVAL_SETTING"."L2_ACCOUNT_2" IS '第二層簽核人員2';
COMMENT ON COLUMN "MOMOAPI"."ACCOUNT_APPROVAL_SETTING"."CREATE_DATE" IS '建立時間';
COMMENT ON COLUMN "MOMOAPI"."ACCOUNT_APPROVAL_SETTING"."UPDATE_DATE" IS '更新時間';

-- Table: ACCOUNT_PERMISSION_PROGRAM (TANPA FOREIGN KEY CONSTRAINTS DULU)
CREATE TABLE "MOMOAPI"."ACCOUNT_PERMISSION_PROGRAM" (
  "PERMISSION_ID" NUMBER(18,0) DEFAULT "MOMOAPI"."ACCOUNT_PERMISSION_PROGRAM_SEQ"."NEXTVAL" NOT NULL,
  "ACCOUNT_ID" NUMBER(18,0),
  "PROGRAM_ID" NUMBER(18,0),
  "ENABLED" VARCHAR2(1 BYTE) DEFAULT 'N',
  "CREATE_DATE" TIMESTAMP (6),
  "CREATE_ACCOUNT" NUMBER(18,0),
  CONSTRAINT "ACCOUNT_PERMISSION_PROGRAM_PK" PRIMARY KEY ("PERMISSION_ID")
) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "MOMO";

COMMENT ON TABLE "MOMOAPI"."ACCOUNT_PERMISSION_PROGRAM" IS '帳號權限';
COMMENT ON COLUMN "MOMOAPI"."ACCOUNT_PERMISSION_PROGRAM"."PERMISSION_ID" IS 'KEY';
COMMENT ON COLUMN "MOMOAPI"."ACCOUNT_PERMISSION_PROGRAM"."ACCOUNT_ID" IS '帳號ID';
COMMENT ON COLUMN "MOMOAPI"."ACCOUNT_PERMISSION_PROGRAM"."PROGRAM_ID" IS '功能選單(子標題)ID';
COMMENT ON COLUMN "MOMOAPI"."ACCOUNT_PERMISSION_PROGRAM"."ENABLED" IS '是否啟用';
COMMENT ON COLUMN "MOMOAPI"."ACCOUNT_PERMISSION_PROGRAM"."CREATE_DATE" IS '建立時間';
COMMENT ON COLUMN "MOMOAPI"."ACCOUNT_PERMISSION_PROGRAM"."CREATE_ACCOUNT" IS '建立ID';

-- Table: AP_ACCOUNT
CREATE TABLE "MOMOAPI"."AP_ACCOUNT" (
  "DEPARTMENT_ID" NUMBER(18,0),
  "SOURCE_ID" VARCHAR2(50 BYTE),
  "ENABLED" VARCHAR2(1 BYTE) DEFAULT 'Y',
  "CREATE_DATE" TIMESTAMP (6),
  "UPDATE_DATE" TIMESTAMP (6)
) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "MOMO";

COMMENT ON TABLE "MOMOAPI"."AP_ACCOUNT" IS 'AP帳號';
COMMENT ON COLUMN "MOMOAPI"."AP_ACCOUNT"."DEPARTMENT_ID" IS '部門別ID';
COMMENT ON COLUMN "MOMOAPI"."AP_ACCOUNT"."SOURCE_ID" IS 'SOURCEID';
COMMENT ON COLUMN "MOMOAPI"."AP_ACCOUNT"."ENABLED" IS '啟用狀態';
COMMENT ON COLUMN "MOMOAPI"."AP_ACCOUNT"."CREATE_DATE" IS '建立時間';
COMMENT ON COLUMN "MOMOAPI"."AP_ACCOUNT"."UPDATE_DATE" IS '更新時間';

-- Table: AP_ACCOUNT_MAP_ACCOUNT
CREATE TABLE "MOMOAPI"."AP_ACCOUNT_MAP_ACCOUNT" (
  "DEPARTMENT_ID" NUMBER(18,0),
  "SOURCE_ID" VARCHAR2(50 BYTE),
  "ACCOUNTNAME" VARCHAR2(300 BYTE),
  "CREATE_DATE" TIMESTAMP (6),
  "UPDATE_DATE" TIMESTAMP (6)
) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "MOMO";

-- Table: AP_KEY_IV
CREATE TABLE "MOMOAPI"."AP_KEY_IV" (
  "KEY_IV_ID" NUMBER(18,0) DEFAULT "MOMOAPI"."AP_KEY_IV_SEQ"."NEXTVAL",
  "SOURCE_ID" VARCHAR2(50 BYTE),
  "KEY" VARCHAR2(250 BYTE),
  "IV" VARCHAR2(250 BYTE),
  "EXPIRED_DATE" TIMESTAMP (6),
  "CREATE_DATE" TIMESTAMP (6)
) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "MOMO";

COMMENT ON TABLE "MOMOAPI"."AP_KEY_IV" IS 'AP_KEY_IV';
COMMENT ON COLUMN "MOMOAPI"."AP_KEY_IV"."KEY_IV_ID" IS '主鍵';
COMMENT ON COLUMN "MOMOAPI"."AP_KEY_IV"."SOURCE_ID" IS 'SOURCEID';
COMMENT ON COLUMN "MOMOAPI"."AP_KEY_IV"."KEY" IS 'KEY';
COMMENT ON COLUMN "MOMOAPI"."AP_KEY_IV"."IV" IS 'IV';
COMMENT ON COLUMN "MOMOAPI"."AP_KEY_IV"."EXPIRED_DATE" IS '到期時間';
COMMENT ON COLUMN "MOMOAPI"."AP_KEY_IV"."CREATE_DATE" IS '建立時間';

-- Table: AP_KEY_TABLE
CREATE TABLE "MOMOAPI"."AP_KEY_TABLE" (
  "DEPARTMENT_ID" VARCHAR2(255 BYTE),
  "CREATE_DATE" DATE,
  "IV" VARCHAR2(255 BYTE),
  "KEY" VARCHAR2(255 BYTE),
  "SOURCE_ID" VARCHAR2(255 BYTE),
  "UPDATE_DATE" DATE
) SEGMENT CREATION DEFERRED
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "MOMO";

-- Table: LOGIN_HISTORY (LOGGING_HISTORY)
CREATE TABLE "MOMOAPI"."LOGIN_HISTORY" (
  "LOGIN_HISTORY_ID" NUMBER(22,0) DEFAULT "MOMOAPI"."LOGIN_HISTORY_ID".nextval,
  "LOGIN_DATE" TIMESTAMP (6),
  "ACCOUNT_ID" NUMBER(22,0)
) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "MOMO";

-- Table: PROGRAM (TANPA FOREIGN KEY CONSTRAINTS DULU)
CREATE TABLE "MOMOAPI"."PROGRAM" (
  "PROGRAM_ID" NUMBER(18,0) DEFAULT "MOMOAPI"."PROGRAM_SEQ"."NEXTVAL" NOT NULL,
  "MENU_ID" NUMBER(18,0),
  "ORDER_NO" NUMBER(10,0),
  "PROGRAM_NAME" NVARCHAR2(150),
  "PROGRAM_URI" VARCHAR2(255 BYTE),
  "CREATE_DATE" TIMESTAMP (6),
  "CREATE_ACCOUNT" NUMBER(18,0),
  "UPDATE_DATE" TIMESTAMP (6),
  "UPDATE_ACCOUNT" NUMBER(18,0),
  CONSTRAINT "PROGRAM_PK" PRIMARY KEY ("PROGRAM_ID")
) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "MOMO";

COMMENT ON COLUMN "MOMOAPI"."PROGRAM"."PROGRAM_ID" IS 'KEY';
COMMENT ON COLUMN "MOMOAPI"."PROGRAM"."MENU_ID" IS '功能選單(父標題)ID';
COMMENT ON COLUMN "MOMOAPI"."PROGRAM"."ORDER_NO" IS '排序';
COMMENT ON COLUMN "MOMOAPI"."PROGRAM"."PROGRAM_NAME" IS '功能名稱';
COMMENT ON COLUMN "MOMOAPI"."PROGRAM"."PROGRAM_URI" IS '功能URI';
COMMENT ON COLUMN "MOMOAPI"."PROGRAM"."CREATE_DATE" IS '建立時間';
COMMENT ON COLUMN "MOMOAPI"."PROGRAM"."CREATE_ACCOUNT" IS '建立ID';
COMMENT ON COLUMN "MOMOAPI"."PROGRAM"."UPDATE_DATE" IS '更新時間';
COMMENT ON COLUMN "MOMOAPI"."PROGRAM"."UPDATE_ACCOUNT" IS '更新ID';

-- Table: ROLE_PERMISSION_PROGRAM (TANPA FOREIGN KEY CONSTRAINTS DULU)
CREATE TABLE "MOMOAPI"."ROLE_PERMISSION_PROGRAM" (
  "PERMISSION_ID" NUMBER(18,0) DEFAULT "MOMOAPI"."ROLE_PERMISSION_PROGRAM_SEQ"."NEXTVAL" NOT NULL,
  "ROLE_ID" NUMBER(18,0),
  "PROGRAM_ID" NUMBER(18,0),
  "CREATE_DATE" TIMESTAMP (6),
  "CREATE_ACCOUNT" NUMBER(18,0),
  CONSTRAINT "ROLE_PERMISSION_PROGRAM_PK" PRIMARY KEY ("PERMISSION_ID")
) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "MOMO";

COMMENT ON COLUMN "MOMOAPI"."ROLE_PERMISSION_PROGRAM"."PERMISSION_ID" IS 'KEY';
COMMENT ON COLUMN "MOMOAPI"."ROLE_PERMISSION_PROGRAM"."ROLE_ID" IS '角色ID';
COMMENT ON COLUMN "MOMOAPI"."ROLE_PERMISSION_PROGRAM"."PROGRAM_ID" IS '功能選單(子標題)ID';
COMMENT ON COLUMN "MOMOAPI"."ROLE_PERMISSION_PROGRAM"."CREATE_DATE" IS '建立時間';
COMMENT ON COLUMN "MOMOAPI"."ROLE_PERMISSION_PROGRAM"."CREATE_ACCOUNT" IS '建立ID';

-- ===============================================
-- TAMBAHKAN FOREIGN KEY CONSTRAINTS SETELAH SEMUA TABEL DIBUAT
-- ===============================================

-- Foreign Key untuk ACCOUNT
ALTER TABLE "MOMOAPI"."ACCOUNT" ADD CONSTRAINT "ACCOUNT_ROLE_FK" 
  FOREIGN KEY ("ROLE_ID") REFERENCES "MOMOAPI"."ROLE" ("ROLE_ID");

ALTER TABLE "MOMOAPI"."ACCOUNT" ADD CONSTRAINT "ACCOUNT_DEPARTMENT_FK" 
  FOREIGN KEY ("DEPARTMENT_ID") REFERENCES "MOMOAPI"."DEPARTMENT" ("DEPARTMENT_ID");

-- Foreign Key untuk ACCOUNT_APPROVAL_SETTING
ALTER TABLE "MOMOAPI"."ACCOUNT_APPROVAL_SETTING" ADD CONSTRAINT "ACCOUNT_APPROVAL_ACCOUNT_FK" 
  FOREIGN KEY ("ACCOUNT_ID") REFERENCES "MOMOAPI"."ACCOUNT" ("ACCOUNT_ID");

-- Foreign Key untuk ACCOUNT_PERMISSION_PROGRAM
ALTER TABLE "MOMOAPI"."ACCOUNT_PERMISSION_PROGRAM" ADD CONSTRAINT "ACCOUNT_PERMISSION_ACCOUNT_FK" 
  FOREIGN KEY ("ACCOUNT_ID") REFERENCES "MOMOAPI"."ACCOUNT" ("ACCOUNT_ID");

-- Foreign Key untuk PROGRAM
ALTER TABLE "MOMOAPI"."PROGRAM" ADD CONSTRAINT "PROGRAM_MENU_FK" 
  FOREIGN KEY ("MENU_ID") REFERENCES "MOMOAPI"."MENU" ("MENU_ID");

ALTER TABLE "MOMOAPI"."PROGRAM" ADD CONSTRAINT "PROGRAM_CREATE_ACCOUNT_FK" 
  FOREIGN KEY ("CREATE_ACCOUNT") REFERENCES "MOMOAPI"."ACCOUNT" ("ACCOUNT_ID");

ALTER TABLE "MOMOAPI"."PROGRAM" ADD CONSTRAINT "PROGRAM_UPDATE_ACCOUNT_FK" 
  FOREIGN KEY ("UPDATE_ACCOUNT") REFERENCES "MOMOAPI"."ACCOUNT" ("ACCOUNT_ID");

-- Foreign Key untuk ROLE_PERMISSION_PROGRAM
ALTER TABLE "MOMOAPI"."ROLE_PERMISSION_PROGRAM" ADD CONSTRAINT "ROLE_PERMISSION_ROLE_FK" 
  FOREIGN KEY ("ROLE_ID") REFERENCES "MOMOAPI"."ROLE" ("ROLE_ID");

ALTER TABLE "MOMOAPI"."ROLE_PERMISSION_PROGRAM" ADD CONSTRAINT "ROLE_PERMISSION_PROGRAM_FK" 
  FOREIGN KEY ("PROGRAM_ID") REFERENCES "MOMOAPI"."PROGRAM" ("PROGRAM_ID");

ALTER TABLE "MOMOAPI"."ROLE_PERMISSION_PROGRAM" ADD CONSTRAINT "ROLE_PERMISSION_CREATE_ACCOUNT_FK" 
  FOREIGN KEY ("CREATE_ACCOUNT") REFERENCES "MOMOAPI"."ACCOUNT" ("ACCOUNT_ID");